theme: jekyll-theme-midnight
title: Daniel Mendelowitz
description: Educator, Unity Developer, 3D Technical Art
author:
  name: Daniel Mendelowitz
  twitter: DanMendelowitz
  picture: https://drive.google.com/file/d/1WOysJ_Y91NzOycYa_SmzHIiofT5wQuYg/view?usp=sharing
twitter_username: DanMendelowitz
github_username: danm3d